### ISSUE TITLE
doesnt compile on stable 1.25.0

### ISSUE THREAD

**Issue by aep** [dalek-cryptography/subtle#13]
not sure if it's supposed to compile on non nighly:

error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/aep/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-0.3.0/src/lib.rs:20:34
   |
20 | #![cfg_attr(feature = "nightly", feature(i128_type))]
   |                                  ^^^^^^^^^^^^^^^^^^^
